services:
  db:
    image: mysql:latest
    container_name: ave-database
    restart: always
    env_file:
      - .env
    ports:
      - "3305:3306"
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
          - mysql_data:/var/lib/mysql
  ave-backend:
    build: .
    container_name: ave-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy  # Wait until MySQL is ready
    env_file:
      - .env
    develop:
      watch:
        - path: .
          action: rebuild
          target: /app
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8000:8000"
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
