"""add fields to user table

Revision ID: 2124b3ca5c99
Revises: 6a49ab1492f7
Create Date: 2026-04-21 16:40:35.027305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2124b3ca5c99'
down_revision: Union[str, None] = '6a49ab1492f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('bucket_image_key', sa.String(length=255), nullable=True))

    # 2. Backfill existing rows with a real value
    op.execute("UPDATE users SET department_id = 1 WHERE department_id IS NULL;")
    op.execute("UPDATE users SET bucket_image_key = 'user/dummy_id' WHERE bucket_image_key IS NULL;")

    op.create_foreign_key(None, 'users', 'department', ['department_id'], ['id'])

    op.alter_column("users", "department_id", nullable=False)
    op.alter_column("users", "bucket_image_key", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'bucket_image_key')
    op.drop_column('users', 'department_id')
    # ### end Alembic commands ###
