"""Table to keep track of used password-reset tokens

Revision ID: 96fea91100cc
Revises: 0560450e8339
Create Date: 2026-02-08 03:58:25.550295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96fea91100cc'
down_revision: Union[str, None] = '0560450e8339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('used_password_reset_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.drop_table('verificationcodes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verificationcodes',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='verificationcodes_pkey'),
    sa.UniqueConstraint('code', name='verificationcodes_code_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('user_id', name='verificationcodes_user_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('used_password_reset_tokens')
    # ### end Alembic commands ###
