"""forein key constraints

Revision ID: 9da1d9d4b82a
Revises: 2124b3ca5c99
Create Date: 2026-04-25 03:22:39.894738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9da1d9d4b82a'
down_revision: Union[str, None] = '2124b3ca5c99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('attendancerecords_user_matric_fkey', 'attendancerecords', type_='foreignkey')
    op.drop_constraint('attendancerecords_fence_code_fkey', 'attendancerecords', type_='foreignkey')
    op.create_foreign_key(None, 'attendancerecords', 'users', ['user_matric'], ['user_matric'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'attendancerecords', 'geofences', ['fence_code'], ['fence_code'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendancerecords', type_='foreignkey')
    op.drop_constraint(None, 'attendancerecords', type_='foreignkey')
    op.create_foreign_key('attendancerecords_fence_code_fkey', 'attendancerecords', 'geofences', ['fence_code'], ['fence_code'])
    op.create_foreign_key('attendancerecords_user_matric_fkey', 'attendancerecords', 'users', ['user_matric'], ['user_matric'])
    # ### end Alembic commands ###
