"""Table to keep track of used password-reset tokens, update

Revision ID: af1f69a98614
Revises: 96fea91100cc
Create Date: 2026-02-08 04:13:41.523471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af1f69a98614'
down_revision: Union[str, None] = '96fea91100cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('used_password_reset_tokens', sa.Column('value', sa.String(), nullable=False))
    op.drop_constraint('used_password_reset_tokens_token_key', 'used_password_reset_tokens', type_='unique')
    op.create_unique_constraint(None, 'used_password_reset_tokens', ['value'])
    op.drop_column('used_password_reset_tokens', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('used_password_reset_tokens', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'used_password_reset_tokens', type_='unique')
    op.create_unique_constraint('used_password_reset_tokens_token_key', 'used_password_reset_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_column('used_password_reset_tokens', 'value')
    # ### end Alembic commands ###
