"""Edited Password Reset Token length

Revision ID: cf1a37f8dc95
Revises: 
Create Date: 2025-03-20 14:09:38.685309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf1a37f8dc95'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('fk1', table_name='sessions')
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['user_matric'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.create_index('fk1', 'sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###
