"""init

Revision ID: e7f292795b30
Revises: 
Create Date: 2026-02-06 08:31:59.497666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7f292795b30'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_matric', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_matric')
    )
    op.create_table('geofences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fence_code', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius', sa.Float(), nullable=False),
    sa.Column('fence_type', sa.String(length=60), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=60), nullable=False),
    sa.Column('time_created', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('creator_matric', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['creator_matric'], ['users.user_matric'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fence_code')
    )
    op.create_table('passwordresettokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_matric'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_passwordresettokens_id'), 'passwordresettokens', ['id'], unique=False)
    op.create_table('attendancerecords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_matric', sa.String(length=50), nullable=False),
    sa.Column('fence_code', sa.String(length=15), nullable=False),
    sa.Column('geofence_name', sa.String(length=60), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('matric_fence_code', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['fence_code'], ['geofences.fence_code'], ),
    sa.ForeignKeyConstraint(['user_matric'], ['users.user_matric'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendancerecords')
    op.drop_index(op.f('ix_passwordresettokens_id'), table_name='passwordresettokens')
    op.drop_table('passwordresettokens')
    op.drop_table('geofences')
    op.drop_table('users')
    # ### end Alembic commands ###
